### ISSUE TITLE
[REQUEST] Sync Attributes from Inputs

### ISSUE THREAD

**Issue by pavelloz** [markmead/alpinejs-character-count#1]
Hello,

Very useful directive :)

What do you think of pulling maxlength from textarea html attribute instead of duplicating it in the call?

I dont know if its possible with Alpine, just asking and poking around :)

**Comment by markmead** [comment]
I did think about doing this but the difficult part is how would you say "this input belongs to this directive", all approaches that I have thought of gets messy.

Any thoughts?

**Comment by pavelloz** [comment]
Hmm, did `x-ref` help with things at all?

**Comment by markmead** [comment]
Yeah, that's the best approach for sure, it's just how to implement it without it being a pain for the developer.

I have some ideas, I'll get a PR in the works.
